### PR TITLE
Feature/itineraryitem

### PR DESCRIPTION
**Pull request by shaynesoh**
please review along with the latest from frontend and verify if its working! not sure if this is the most ideal way

### CODE REVIEW

**Comment by benchan79** [comment]
Reviewed both and they look good. Nice work.

**Review by benchan79 — APPROVED** [review]
Reviewed both and they look good. Nice work.

**Comment by nbtai7777** [comment]
Nice work.

**Comment by benchan79** [comment]
Need to merge first before closing.

**Review by justan-kj — APPROVED** [review]

**Pull request merged**
